#!/bin/bash

echo "✅ Checking code formatting..."
npm run test
if [ $? -ne 0 ]; then
  echo "❌ The code is not formatted. Use 'dotnet format'"
  exit 1
fi

echo "✅ Running tests..."
npm run lint
if [ $? -ne 0 ]; then
  echo "❌ The tests failed."
  exit 1
fi
